# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy_code:
#     name: deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: step1
#         env:
#           NAME: ${{secrets.NAME}}
#         run: echo $NAME















name: Deploy Code
on:
  push:
    branches:
      - main

jobs:
  deploy code job:
    name: deploy on aws
    runs-on: ubuntu-latest
    steps:
      - name: first step
        env:
          NAME: ${{secrets.NAME}}
        run: exho "Hello World" $NAME

      - name: second setp
        run: echo "Hello"
